# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnoutPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additonaluserdata',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='additonaluserdata',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagetest',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='imagetest',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('PARROT', 'Parrot'), ('EXOTIC', 'Exotic')], default='DOG', max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.FileField(blank=True, upload_to='pet_profile_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('PARROT', 'Parrot'), ('EXOTIC', 'Exotic')], default='DOG', max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Userpicture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
