# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnoutPage', '0002_additonaluserdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(upload_to='pet_profile_images'),
        ),
    ]
