# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnoutPage', '0002_auto_20180313_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b'profile_images'),
        ),
    ]
