# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SnoutPage', '0003_auto_20180328_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='person',
        ),
    ]
