# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnoutPage', '0004_auto_20180322_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pet_profile_images'),
        ),
    ]
