# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SnoutPage', '0006_auto_20180323_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetest',
            options={'verbose_name_plural': 'Images'},
        ),
    ]
