# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnoutPage', '0008_auto_20180323_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(upload_to='pet_profile_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
