# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SnoutPage', '0010_auto_20180326_1711'),
        ('SnoutPage', '0012_auto_20180326_2128'),
    ]

    operations = [
    ]
