# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SnoutPage', '0013_merge_20180326_2300'),
        ('SnoutPage', '0010_auto_20180325_1325'),
    ]

    operations = [
    ]
